linters-settings:
  gocritic:
    enabled-tags:
      # - performance
      - diagnostic
      - experimental
      - opinionated
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: github.com/iiiceoo/requeueip
  # goheader:
  #   template-path: scripts/boilerplate.txt

linters:
  disable-all: true
  enable:
    # - goheader
    - staticcheck
    - gosimple
    - typecheck
    - govet
    
    - gofmt
    - goimports
    - stylecheck
    - whitespace
    
    - bodyclose
    - noctx
    - gocritic
    - gocheckcompilerdirectives
    - goprintffuncname
    - misspell
    - nolintlint

run:
  timeout: 1m