/*
Copyright 2024 The RequeueIP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package calico

import (
	"context"
	"reflect"

	calicov1 "github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	requeueipv1 "github.com/iiiceoo/requeueip/api/v1"
	"github.com/iiiceoo/requeueip/pkg/consts"
)

func NewSYNCReconciler(c client.Client) *syncReconciler {
	return &syncReconciler{
		client: c,
	}
}

type syncReconciler struct {
	client client.Client
}

func (r *syncReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&requeueipv1.Subnet{}, builder.WithPredicates(
			predicate.NewPredicateFuncs(func(object client.Object) bool {
				_, sync := object.GetAnnotations()[consts.AnnoCalicoSYNC]
				return sync
			}),
		)).
		Owns(&calicov1.IPPool{}).
		Complete(r)
}

var _ reconcile.Reconciler = &syncReconciler{}

func (r *syncReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	var rn requeueipv1.Subnet
	if err := r.client.Get(ctx, req.NamespacedName, &rn); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	// The Subnet has been deleted, do nothing, OwnerReference will ensure that the
	// relevant Calico IPPool is recycled.
	if !rn.DeletionTimestamp.IsZero() {
		return ctrl.Result{}, nil
	}

	return reconcile.Result{}, r.ensureCalicoIPPool(ctx, &rn)
}

// ensureCalicoIPPool updates Calico IPPool with the spec generated by Subnet,
// or creates it if it does not exist.
func (r *syncReconciler) ensureCalicoIPPool(ctx context.Context, subnet *requeueipv1.Subnet) error {
	spec := &calicov1.IPPoolSpec{
		CIDR:         subnet.Spec.CIDR,
		VXLANMode:    calicov1.VXLANModeNever,
		IPIPMode:     calicov1.IPIPModeNever,
		NATOutgoing:  true,
		Disabled:     true,
		BlockSize:    int(*subnet.Spec.BlockSize),
		NodeSelector: "!all()",
	}

	var cp calicov1.IPPool
	if err := r.client.Get(ctx, types.NamespacedName{Name: subnet.Name}, &cp); err != nil {
		if !apierrors.IsNotFound(err) {
			return err
		}

		cp := &calicov1.IPPool{
			ObjectMeta: metav1.ObjectMeta{
				Name: subnet.Name,
			},
			Spec: *spec,
		}
		if err := controllerutil.SetControllerReference(subnet, cp, r.client.Scheme()); err != nil {
			return err
		}
		return client.IgnoreAlreadyExists(r.client.Create(ctx, cp))
	}

	if reflect.DeepEqual(&cp.Spec, spec) {
		return nil
	}
	cp.Spec = *spec

	return r.client.Update(ctx, &cp)
}
