apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "requeueip.controller" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "requeueip.controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "requeueip.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "requeueip.controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "requeueip.controller" . }}
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: requeueip-controller
        image: "{{ .Values.controller.image.registry }}/{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default (print "v" .Chart.AppVersion) }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        command:
        - requeueip-controller
        args:
        - run
        ports:
        - name: metrics
          containerPort: 8443
          protocol: TCP
        - name: webhook
          containerPort: 9443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: {{ .Values.controller.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.controller.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.controller.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.controller.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.controller.livenessProbe.successThreshold }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: {{ .Values.controller.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.controller.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.controller.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.controller.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.controller.readinessProbe.successThreshold }}
        resources:
          {{- toYaml .Values.controller.resources | nindent 10}}
        volumeMounts:
        - name: requeueip-controller-config
          mountPath: /etc/requeueip
          readOnly: true
        - name: webhook-cert
          mountPath: /etc/requeueip/webhook
          readOnly: true
      volumes:
      - name: requeueip-controller-config
        configMap:
          name: {{ include "requeueip.controller" . }}-config
      - name: webhook-cert
        secret:
          secretName: {{ include "requeueip.fullname" . }}-webhook-cert