apiVersion: v1
kind: Service
metadata:
  name: {{ include "requeueip.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "requeueip.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    {{- include "requeueip.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.metricsService.port }}
    targetPort: metrics
    protocol: TCP