apiVersion: v1
kind: Service
metadata:
  name: {{ include "requeueip.controller" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "requeueip.controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.metricsService.type }}
  selector:
    {{- include "requeueip.controller.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.controller.metricsService.port }}
    targetPort: metrics
    protocol: TCP