{{- if .Values.multus.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "requeueip.multus" . }}-admin
rules:
- apiGroups: ["k8s.cni.cncf.io"]
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "requeueip.multus" . }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "requeueip.multus" . }}-admin
subjects:
- kind: ServiceAccount
  name: {{ include "requeueip.multus" . }}
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "requeueip.multus" . }}
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "requeueip.multus" . }}-config
  namespace: kube-system
  labels:
    {{- include "requeueip.multus.labels" . | nindent 4 }}
data:
  daemon-config.json: |-
    {{- with .Values.multus.config }}
    {{- toJson . | nindent 4}}
    {{- end }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "requeueip.multus" . }}
  namespace: kube-system
  labels:
    {{- include "requeueip.multus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "requeueip.multus.selectorLabels" . | nindent 6 }}
  {{- with .Values.multus.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "requeueip.multus.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      serviceAccountName: {{ include "requeueip.multus" . }}
      {{- with .Values.multus.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: kube-multus
        image: "{{ .Values.multus.image.registry }}/{{ .Values.multus.image.repository }}:{{ .Values.multus.image.tag }}"
        command: [ "/usr/src/multus-cni/bin/multus-daemon" ]
        resources:
          {{- toYaml .Values.multus.resources | nindent 10}}
        securityContext:
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /opt/cni/bin
        - name: host-run
          mountPath: /host/run
        - name: host-var-lib-cni-multus
          mountPath: /var/lib/cni/multus
        - name: host-var-lib-kubelet
          mountPath: /var/lib/kubelet
          mountPropagation: HostToContainer
        - name: host-run-k8s-cni-cncf-io
          mountPath: /run/k8s.cni.cncf.io
        - name: host-run-netns
          mountPath: /run/netns
          mountPropagation: HostToContainer
        - name: multus-daemon-config
          mountPath: /etc/cni/net.d/multus.d
          readOnly: true
        - name: hostroot
          mountPath: /hostroot
          mountPropagation: HostToContainer
        env:
        - name: MULTUS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      initContainers:
      - name: install-multus-binary
        image: "{{ .Values.multus.image.registry }}/{{ .Values.multus.image.repository }}:{{ .Values.multus.image.tag }}"
        command:
        - "/usr/src/multus-cni/bin/install_multus"
        - "-d"
        - "/host/opt/cni/bin"
        - "-t"
        - "thick"
        resources:
          requests:
            cpu: "10m"
            memory: "15Mi"
        securityContext:
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
      - name: hostroot
        hostPath:
          path: /
      - name: multus-daemon-config
        configMap:
          name: {{ include "requeueip.multus" . }}-config
          items:
          - key: daemon-config.json
            path: daemon-config.json
      - name: host-run
        hostPath:
          path: /run
      - name: host-var-lib-cni-multus
        hostPath:
          path: /var/lib/cni/multus
      - name: host-var-lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: host-run-k8s-cni-cncf-io
        hostPath:
          path: /run/k8s.cni.cncf.io
      - name: host-run-netns
        hostPath:
          path: /run/netns/
{{- end -}}