{{- if .Values.multus.enabled -}}
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.multus.nad.name }}
  namespace: kube-system
spec:
  config: {{ .Values.multus.nad.config | quote }}
{{- end -}}