---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "requeueip.fullname" . }}-admin
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - requeueip.sauto4.io
  resources:
  - sautoipblocks
  - sautoippools
  - sautoips
  - sautosubnets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - requeueip.sauto4.io
  resources:
  - sautoippools/status
  - sautosubnets/status
  verbs:
  - get
  - patch
  - update
