apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "requeueip.daemon" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "requeueip.controller" . }}
  namespace: {{ .Release.Namespace }}