openapi: "3.0.0"
info:
  version: 1.0.0
  title: RequeueIP CNI
  description: Wrapper for CNI requests and responses.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://unix:/
paths:
  /health:
    get:
      operationId: health
      responses:
        '200':
          description: RequeueIP daemon is healthy.
  /ips:
    post:
      operationId: cmdAdd
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddArgs'
        required: true
      responses:
        '200':
          description: Successfully assigned IP addresses.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
        default:
          description: Failed to assgin IP addresses.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: string
    AddArgs:
      type: object
      properties:
        ipv4:
          type: boolean
        ipv6:
          type: boolean
        podNamespace:
          type: string
        podName:
          type: string
      required:
      - ipv4
      - ipv6
      - podNamespace
      - podName
    Result:
      type: object
      properties:
        ips:
          type: array
          items:
            $ref: "#/components/schemas/IPConfig"
        routes:
          type: array
          items:
            $ref: "#/components/schemas/Route"
        dns:
          type: object
          $ref: "#/components/schemas/DNS"
      required:
      - ips
    IPConfig:
      type: object
      properties:
        address:
          type: string
        gateway:
          type: string
      required:
      - address
    Route:
      type: object
      properties:
        dst:
          type: string
        gw:
          type: string
      required:
      - dst
    DNS:
      type: object
      properties:
        nameservers:
          type: array
          items:
            type: string
        domain:
          type: string
        search:
          type: array
          items:
            type: string
        options:
          type: array
          items:
            type: string
      required:
      - nameservers