# Default values for RequeueIP.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local
multus:
  enabled: true
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  image:
    registry: ghcr.io/k8snetworkplumbingwg
    repository: multus-cni
    tag: snapshot-thick
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "2"
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 128Mi
  imagePullSecrets: []
  config:
    cniVersion: 0.3.1
    chrootDir: /hostroot
    logLevel: verbose
    logToStderr: true
    cniConfigDir: /host/etc/cni/net.d
    multusAutoconfigDir: /host/etc/cni/net.d
    multusConfigFile: auto
    socketDir: /host/run/multus
  nad:
    name: calico-requeueip
    config: |-
      {
        "name": "static-network",
        "cniVersion": "0.3.1",
        "plugins": [
          {
            "type": "calico",
            "log_level": "info",
            "log_file_path": "/var/log/calico/cni/cni.log",
            "datastore_type": "kubernetes",
            "ipam": {
                "type": "requeueip",
                "ipv4": true,
                "ipv6": false
            },
            "policy": {
                "type": "k8s"
            },
            "kubernetes": {
                "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
            }
          },
          {
            "type": "portmap",
            "snat": true,
            "capabilities": {"portMappings": true}
          },
          {
            "type": "bandwidth",
            "capabilities": {"bandwidth": true}
          }
        ]
      }
daemon:
  socket: /var/run/requeueip/cni.sock
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  image:
    registry: ghcr.io/requeueip
    repository: requeueipd
    tag: ""
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  imagePullSecrets: []
  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
controller:
  replicas: 1
  image:
    registry: ghcr.io/requeueip
    repository: requeueip-controller
    tag: ""
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi
  imagePullSecrets: []
  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  metricsService:
    type: ClusterIP
    port: 8443
webhookService:
  type: ClusterIP
  port: 9443
tls:
  auto:
    caValidityDuration: 3650
    certValidityDuration: 3650
    extraIPAddresses: []
    extraDNSNames: []