apiVersion: requeueip.io/v1
kind: Subnet
metadata:
  name: smoke-ipv4-subnet
spec:
  cidr: 10.0.0.0/24
---
apiVersion: requeueip.io/v1
kind: Subnet
metadata:
  name: smoke-ipv6-subnet
spec:
  cidr: fd00::/120