#!/usr/bin/env bash

# Copyright 2024 The RequeueIP Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

# CONST
PROJECT_ROOT=$(dirname ${BASH_SOURCE[0]})/..
OAPI_CODEGEN_TMP_PATH=${OAPI_CODEGEN_TMP_PATH:-${PROJECT_ROOT}/.oapi_codegen_tmp}

# ENV
# Define the output path of the source code generated by oapi-codegen.
OUTPUT_BASE_PATH=${OUTPUT_BASE_PATH:-${PROJECT_ROOT}/oapi/v1}
OUTPUT_FILE_NAME=${OUTPUT_FILE_NAME:-cni.gen.go}
OUTPUT=${OUTPUT:-${OUTPUT_BASE_PATH}/${OUTPUT_FILE_NAME}}

CONFIG="${OUTPUT_BASE_PATH}/cni.cfg.yaml"
if [[ ! -f ${CONFIG} ]];then
  echo "Error: oapi-codegen config ${CONFIG} does not exist"
  exit 1
fi

SPEC="${OUTPUT_BASE_PATH}/openapi3.yaml"
if [[ ! -f ${SPEC} ]];then
  echo "Error: OpenAPI(v3) spec ${SPEC} does not exist"
  exit 1
fi


clean() {
  rm -f ${OUTPUT}
}

generate() {
  oapi-codegen --config ${CONFIG} -o ${OUTPUT} ${SPEC}
}

verify() {
  trap "cleanup" EXIT SIGINT

  mkdir -p ${OAPI_CODEGEN_TMP_PATH}
  cp -a ${OUTPUT_BASE_PATH}/* ${OAPI_CODEGEN_TMP_PATH}

  generate

  ret=0
  diff -Naupr ${OUTPUT_BASE_PATH} ${OAPI_CODEGEN_TMP_PATH} || ret=$?

  if [[ $ret -eq 0 ]];then
    echo "OpenAPI(v3) for RequeueIP is up to date"
  else
    echo "Error: OpenAPI(v3) for RequeueIP is out of date, run 'make gen.oapi'"
    exit 1
  fi
}

cleanup() {
  rm -rf ${OAPI_CODEGEN_TMP_PATH}
}

help() {
    echo "help"
}

main() {
  case ${1:-none} in
    clean)
      clean
      ;;
    gen)
      clean
      generate
      ;;
    verify)
      verify
      ;;
    *|help|-h|--help)
      help
      ;;
  esac
}

main "$*"