apiVersion: v1
kind: Service
metadata:
  name: {{ include "requeueip.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "requeueip.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    {{- include "requeueip.selectorLabels" . | nindent 4 }}
  ports:
  - name: webhook
    port: {{ .Values.webhookService.port }}
    targetPort: webhook
    protocol: TCP